require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Sendgrid::LogsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Sendgrid::Log. As you add validations to Sendgrid::Log, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Sendgrid::LogsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sendgrid_logs as @sendgrid_logs" do
      log = Sendgrid::Log.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:sendgrid_logs)).to eq([log])
    end
  end

  describe "GET show" do
    it "assigns the requested sendgrid_log as @sendgrid_log" do
      log = Sendgrid::Log.create! valid_attributes
      get :show, {:id => log.to_param}, valid_session
      expect(assigns(:sendgrid_log)).to eq(log)
    end
  end

  describe "GET new" do
    it "assigns a new sendgrid_log as @sendgrid_log" do
      get :new, {}, valid_session
      expect(assigns(:sendgrid_log)).to be_a_new(Sendgrid::Log)
    end
  end

  describe "GET edit" do
    it "assigns the requested sendgrid_log as @sendgrid_log" do
      log = Sendgrid::Log.create! valid_attributes
      get :edit, {:id => log.to_param}, valid_session
      expect(assigns(:sendgrid_log)).to eq(log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sendgrid::Log" do
        expect {
          post :create, {:sendgrid_log => valid_attributes}, valid_session
        }.to change(Sendgrid::Log, :count).by(1)
      end

      it "assigns a newly created sendgrid_log as @sendgrid_log" do
        post :create, {:sendgrid_log => valid_attributes}, valid_session
        expect(assigns(:sendgrid_log)).to be_a(Sendgrid::Log)
        expect(assigns(:sendgrid_log)).to be_persisted
      end

      it "redirects to the created sendgrid_log" do
        post :create, {:sendgrid_log => valid_attributes}, valid_session
        expect(response).to redirect_to(Sendgrid::Log.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sendgrid_log as @sendgrid_log" do
        post :create, {:sendgrid_log => invalid_attributes}, valid_session
        expect(assigns(:sendgrid_log)).to be_a_new(Sendgrid::Log)
      end

      it "re-renders the 'new' template" do
        post :create, {:sendgrid_log => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sendgrid_log" do
        log = Sendgrid::Log.create! valid_attributes
        put :update, {:id => log.to_param, :sendgrid_log => new_attributes}, valid_session
        log.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested sendgrid_log as @sendgrid_log" do
        log = Sendgrid::Log.create! valid_attributes
        put :update, {:id => log.to_param, :sendgrid_log => valid_attributes}, valid_session
        expect(assigns(:sendgrid_log)).to eq(log)
      end

      it "redirects to the sendgrid_log" do
        log = Sendgrid::Log.create! valid_attributes
        put :update, {:id => log.to_param, :sendgrid_log => valid_attributes}, valid_session
        expect(response).to redirect_to(log)
      end
    end

    describe "with invalid params" do
      it "assigns the sendgrid_log as @sendgrid_log" do
        log = Sendgrid::Log.create! valid_attributes
        put :update, {:id => log.to_param, :sendgrid_log => invalid_attributes}, valid_session
        expect(assigns(:sendgrid_log)).to eq(log)
      end

      it "re-renders the 'edit' template" do
        log = Sendgrid::Log.create! valid_attributes
        put :update, {:id => log.to_param, :sendgrid_log => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sendgrid_log" do
      log = Sendgrid::Log.create! valid_attributes
      expect {
        delete :destroy, {:id => log.to_param}, valid_session
      }.to change(Sendgrid::Log, :count).by(-1)
    end

    it "redirects to the sendgrid_logs list" do
      log = Sendgrid::Log.create! valid_attributes
      delete :destroy, {:id => log.to_param}, valid_session
      expect(response).to redirect_to(sendgrid_logs_url)
    end
  end

end
